authorName: Shachar Hananya
experimentName: Method 4 - EC - ROYSDATA - EC
maxExecDuration: 24h
maxTrialNum: 500
searchSpacePath: search_space_4.json
trainingServicePlatform: local
trial:
  codeDir: /home/dsi/shacharh/Projects/MissingVals/Graph-Feature-Propagation
  command: python main.py --nni 4 --use_existence_cols True --dataset RoysData --missing_ratio -1 --use_existence_cols True
  gpuNum: 0
trialConcurrency: 10
tuner:
  builtinTunerName: TPE
useAnnotation: false
