authorName: Shachar Hananya
experimentName: Method 4 - BANKNOTE - NEC
maxExecDuration: 200h
maxTrialNum: 500
searchSpacePath: search_space_4.json
trainingServicePlatform: local
trial:
  codeDir: /home/dsi/shacharh/Projects/MissingVals/Graph-Feature-Propagation
  command: python main.py --nni 4 --dataset Banknote --missing_ratio 90 --use_existence_cols
    False
  gpuNum: 0
trialConcurrency: 1
tuner:
  builtinTunerName: TPE
useAnnotation: false
