authorName: Shachar Hananya
experimentName: Method 4
trialConcurrency: 10
maxExecDuration: 200h
maxTrialNum: 500
trainingServicePlatform: local
# The path to Search Space
searchSpacePath: search_space_4.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
  # The path and the running command of trial
trial:
  command: python main.py --nni 4
  codeDir: /home/dsi/shacharh/Projects/MissingVals/Graph-Feature-Propagation
  gpuNum: 0