authorName: Shachar Hananya
experimentName: Method 3 - NEC
trialConcurrency: 1
maxExecDuration: 72h
maxTrialNum: 500
trainingServicePlatform: local
# The path to Search Space
searchSpacePath: search_space_3.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
  # The path and the running command of trial
trial:
  command: python main.py --nni 3 --use_existence_cols False
  codeDir: /home/dsi/shacharh/Projects/MissingVals/Graph-Feature-Propagation
  gpuNum: 0