authorName: Shachar Hananya
experimentName: Method 2 - BANKNOTE - EC
maxExecDuration: 24h
maxTrialNum: 500
searchSpacePath: search_space_2.json
trainingServicePlatform: local
trial:
  codeDir: /home/dsi/shacharh/Projects/MissingVals/Graph-Feature-Propagation
  command: python main.py --nni 2 --dataset Banknote --missing_ratio 90 --use_existence_cols
    True
  gpuNum: 0
trialConcurrency: 1
tuner:
  builtinTunerName: TPE
useAnnotation: false
