authorName: Shachar Hananya
experimentName: Method 6
trialConcurrency: 1
maxExecDuration: 72h
maxTrialNum: 500
trainingServicePlatform: local
# The path to Search Space
searchSpacePath: search_space_6.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
  # The path and the running command of trial
trial:
  command: python main.py --nni 6
  codeDir: /home/dsi/shacharh/Projects/MissingVals/Graph-Feature-Propagation
  gpuNum: 0 