authorName: Shachar Hananya
experimentName: Method 6 - DIABETES - NEC
maxExecDuration: 72h
maxTrialNum: 500
searchSpacePath: search_space_6.json
trainingServicePlatform: local
trial:
  codeDir: /home/dsi/shacharh/Projects/MissingVals/Graph-Feature-Propagation
  command: python main.py --nni 6 --dataset Diabetes --missing_ratio 90 --use_existence_cols
    False
  gpuNum: 0
trialConcurrency: 1
tuner:
  builtinTunerName: TPE
useAnnotation: false
