authorName: Shachar Hananya
experimentName: Method 1 - RONSDATA - NEC
maxExecDuration: 24h
maxTrialNum: 500
searchSpacePath: search_space_1.json
trainingServicePlatform: local
trial:
  codeDir: /home/dsi/shacharh/Projects/MissingVals/Graph-Feature-Propagation
  command: python main.py --nni 1 --dataset RonsData --missing_ratio -1 --use_existence_cols
    False
  gpuNum: 0
trialConcurrency: 1
tuner:
  builtinTunerName: TPE
useAnnotation: false
