authorName: Shachar Hananya
experimentName: Method 1 - EC
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 500
trainingServicePlatform: local
# The path to Search Space
searchSpacePath: search_space_1.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
  # The path and the running command of trial
trial:
  command: python main.py --nni 1 --use_existence_cols True
  codeDir: /home/dsi/shacharh/Projects/MissingVals/Graph-Feature-Propagation
  gpuNum: 0